# Generated by Django 5.2.4 on 2026-07-23 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('pokemon_kr', '포켓몬 한글판'), ('pokemon_jp', '포켓몬 일본판'), ('onepiece_kr', '원피스 한글판'), ('digimon_kr', '디지몬 한글판')], db_index=True, max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('card_count', models.PositiveIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pricesite_expansion',
                'ordering': ['-release_date'],
                'unique_together': {('game_type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('pokemon_kr', '포켓몬 한글판'), ('pokemon_jp', '포켓몬 일본판'), ('onepiece_kr', '원피스 한글판'), ('digimon_kr', '디지몬 한글판')], db_index=True, max_length=20)),
                ('source_id', models.PositiveIntegerField(help_text='pricehub 원본 Card PK — 가격 API 조회에 사용')),
                ('card_number', models.CharField(max_length=20)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('rarity', models.CharField(blank=True, max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('latest_market_price', models.PositiveIntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('expansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='pricesite.expansion')),
            ],
            options={
                'db_table': 'pricesite_card',
                'ordering': ['card_number'],
                'indexes': [models.Index(fields=['game_type', 'expansion', 'card_number'], name='pricesite_c_game_ty_37d667_idx')],
                'unique_together': {('game_type', 'source_id')},
            },
        ),
    ]
