# Generated by Django 5.2.4 on 2026-07-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_mirror',
            field=models.BooleanField(default=False, help_text='포켓몬 일본판 미러 카드 여부'),
        ),
    ]
