# Generated by Django 5.2.4 on 2026-01-07 04:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='예: m2', max_length=20, unique=True, verbose_name='확장팩번호')),
                ('name', models.CharField(help_text='예: 인페르노X', max_length=100, verbose_name='시리즈명')),
                ('image_url', models.URLField(max_length=500, verbose_name='확장팩 이미지')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='출시일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '확장팩',
                'verbose_name_plural': '확장팩 목록',
                'db_table': 'expansion',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='예: 001', max_length=10, verbose_name='카드번호')),
                ('name', models.CharField(help_text='예: 뚜벅쵸', max_length=100, verbose_name='카드명')),
                ('rarity', models.CharField(choices=[('UR', 'UR'), ('SSR', 'SSR'), ('SR', 'SR'), ('RR', 'RR'), ('RRR', 'RRR'), ('CHR', 'CHR'), ('CSR', 'CSR'), ('BWR', 'BWR'), ('AR', 'AR'), ('SAR', 'SAR'), ('HR', 'HR'), ('R', 'R'), ('U', 'U'), ('C', 'C'), ('몬스터볼', '몬스터볼'), ('마스터볼', '마스터볼'), ('이로치', '이로치')], max_length=20, verbose_name='레어도')),
                ('shop_product_code', models.CharField(help_text='예: PKM-m2-001-K', max_length=50, unique=True, verbose_name='네이버상품코드')),
                ('image_url', models.URLField(max_length=500, verbose_name='이미지주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('expansion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='pricehub.expansion', verbose_name='확장팩')),
            ],
            options={
                'verbose_name': '싱글카드',
                'verbose_name_plural': '싱글카드 목록',
                'db_table': 'card',
                'ordering': ['expansion', 'card_number'],
            },
        ),
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='판매가')),
                ('source', models.CharField(default='naver_shopping', max_length=50, verbose_name='출처')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집시간')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricehub.card', verbose_name='카드')),
            ],
            options={
                'verbose_name': '카드가격',
                'verbose_name_plural': '카드가격 히스토리',
                'db_table': 'card_price',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['card', '-collected_at'], name='card_price_card_id_05bbc6_idx'), models.Index(fields=['collected_at'], name='card_price_collect_4f5ba2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['expansion', 'card_number'], name='card_expansi_4b0358_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['shop_product_code'], name='card_shop_pr_e3a770_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('expansion', 'card_number')},
        ),
    ]
