# Generated by Django 5.2.10 on 2026-01-07 05:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetStorePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='판매가')),
                ('store_name', models.CharField(default='TCG999', max_length=100, verbose_name='타겟 판매처')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집시간')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_prices', to='pricehub.card', verbose_name='카드')),
            ],
            options={
                'verbose_name': '타겟 스토어 가격',
                'verbose_name_plural': '타겟 스토어 가격 히스토리',
                'db_table': 'target_store_price',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['card', '-collected_at'], name='target_stor_card_id_43ced2_idx'), models.Index(fields=['store_name', '-collected_at'], name='target_stor_store_n_10d600_idx'), models.Index(fields=['collected_at'], name='target_stor_collect_c320a8_idx')],
            },
        ),
    ]
