# Generated by Django 5.2.10 on 2026-01-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0002_targetstoreprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('UR', 'UR'), ('SSR', 'SSR'), ('SR', 'SR'), ('RR', 'RR'), ('RRR', 'RRR'), ('CHR', 'CHR'), ('CSR', 'CSR'), ('BWR', 'BWR'), ('AR', 'AR'), ('SAR', 'SAR'), ('HR', 'HR'), ('R', 'R'), ('U', 'U'), ('C', 'C'), ('몬스터볼', '몬스터볼'), ('마스터볼', '마스터볼'), ('이로치', '이로치'), ('미러', '미러')], max_length=20, verbose_name='레어도'),
        ),
    ]
