# Generated by Django 5.2.10 on 2026-01-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0003_alter_card_rarity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together=set(),
        ),
    ]
