# Generated by Django 5.2.4 on 2026-01-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0005_alter_card_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('UR', 'UR'), ('SSR', 'SSR'), ('SR', 'SR'), ('RR', 'RR'), ('RRR', 'RRR'), ('CHR', 'CHR'), ('CSR', 'CSR'), ('BWR', 'BWR'), ('AR', 'AR'), ('SAR', 'SAR'), ('HR', 'HR'), ('MUR', 'MUR'), ('MA', 'MA'), ('R', 'R'), ('U', 'U'), ('C', 'C'), ('몬스터볼', '몬스터볼'), ('마스터볼', '마스터볼'), ('볼 미러', '볼 미러'), ('타입 미러', '타입 미러'), ('로켓단 미러', '로켓단 미러'), ('이로치', '이로치'), ('미러', '미러')], max_length=20, verbose_name='레어도'),
        ),
    ]
