# Generated by Django 5.2.4 on 2026-02-02 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0006_alter_card_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnePieceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_product_code', models.CharField(max_length=50, unique=True, verbose_name='상품코드')),
                ('card_number', models.CharField(max_length=10, verbose_name='카드번호')),
                ('name', models.CharField(max_length=100, verbose_name='카드명')),
                ('rarity', models.CharField(choices=[('SEC', 'SEC'), ('SL', 'SL'), ('SP', 'SP'), ('SR', 'SR'), ('L', 'L'), ('R', 'R'), ('UC', 'UC'), ('C', 'C'), ('P', 'P')], max_length=20, verbose_name='레어도')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '원피스 카드',
                'verbose_name_plural': '원피스 카드 목록',
                'db_table': 'onepiece_card',
                'ordering': ['expansion', 'card_number'],
            },
        ),
        migrations.CreateModel(
            name='OnePieceExpansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='확장팩 코드')),
                ('name', models.CharField(max_length=100, verbose_name='확장팩명')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='출시일')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '원피스 확장팩',
                'verbose_name_plural': '원피스 확장팩 목록',
                'db_table': 'onepiece_expansion',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnePieceCardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
                ('source', models.CharField(max_length=100, verbose_name='판매처')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricehub.onepiececard', verbose_name='카드')),
            ],
            options={
                'verbose_name': '원피스 카드 가격',
                'verbose_name_plural': '원피스 카드 가격 목록',
                'db_table': 'onepiece_card_price',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.AddField(
            model_name='onepiececard',
            name='expansion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='pricehub.onepieceexpansion', verbose_name='확장팩'),
        ),
        migrations.CreateModel(
            name='OnePieceTargetStorePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
                ('store_name', models.CharField(max_length=100, verbose_name='판매처')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_prices', to='pricehub.onepiececard', verbose_name='카드')),
            ],
            options={
                'verbose_name': '원피스 TCG999 가격',
                'verbose_name_plural': '원피스 TCG999 가격 목록',
                'db_table': 'onepiece_target_store_price',
                'ordering': ['-collected_at'],
            },
        ),
    ]
