# Generated by Django 5.2.4 on 2026-02-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0007_onepiececard_onepieceexpansion_onepiececardprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onepiececard',
            name='card_number',
            field=models.CharField(max_length=20, verbose_name='카드번호'),
        ),
        migrations.AlterField(
            model_name='onepiececard',
            name='rarity',
            field=models.CharField(choices=[('SEC', 'SEC'), ('SL', 'SL'), ('SP', 'SP'), ('SR', 'SR'), ('L', 'L'), ('R', 'R'), ('UC', 'UC'), ('C', 'C'), ('P', 'P'), ('P-SEC', 'P-SEC'), ('P-SR', 'P-SR'), ('P-L', 'P-L'), ('P-R', 'P-R'), ('P-UC', 'P-UC'), ('P-C', 'P-C'), ('SP-SEC', 'SP-SEC'), ('SP-SR', 'SP-SR'), ('SP-L', 'SP-L'), ('SP-R', 'SP-R'), ('SP-UC', 'SP-UC'), ('SP-C', 'SP-C')], max_length=20, verbose_name='레어도'),
        ),
    ]
