# Generated by Django 5.2.4 on 2026-02-02 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0008_alter_onepiececard_card_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onepiecetargetstoreprice',
            options={'ordering': ['-collected_at'], 'verbose_name': '원피스 카드킹덤 가격', 'verbose_name_plural': '원피스 카드킹덤 가격 목록'},
        ),
        migrations.AddField(
            model_name='onepiececard',
            name='is_manga',
            field=models.BooleanField(default=False, verbose_name='망가(슈퍼패러렐)'),
        ),
        migrations.AlterField(
            model_name='onepiecetargetstoreprice',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardkingdom_prices', to='pricehub.onepiececard', verbose_name='카드'),
        ),
    ]
