# Generated by Django 5.2.4 on 2026-02-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0009_alter_onepiecetargetstoreprice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JapanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_product_code', models.CharField(max_length=50, unique=True, verbose_name='상품코드')),
                ('card_number', models.CharField(max_length=20, verbose_name='카드번호')),
                ('name', models.CharField(max_length=100, verbose_name='카드명')),
                ('rarity', models.CharField(choices=[('UR', 'UR'), ('MUR', 'MUR'), ('SSR', 'SSR'), ('SR', 'SR'), ('SAR', 'SAR'), ('HR', 'HR'), ('CSR', 'CSR'), ('CHR', 'CHR'), ('AR', 'AR'), ('BWR', 'BWR'), ('마스터볼', '마스터볼'), ('몬스터볼', '몬스터볼'), ('이로치', '이로치'), ('미러', '미러'), ('RRR', 'RRR'), ('RR', 'RR'), ('R', 'R'), ('U', 'U'), ('C', 'C')], max_length=20, verbose_name='레어도')),
                ('is_mirror', models.BooleanField(default=False, verbose_name='미러')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '포켓몬 일본판 카드',
                'verbose_name_plural': '포켓몬 일본판 카드 목록',
                'db_table': 'japan_card',
                'ordering': ['expansion', 'card_number'],
            },
        ),
        migrations.CreateModel(
            name='JapanExpansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='확장팩 코드')),
                ('name', models.CharField(max_length=200, verbose_name='확장팩명')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='출시일')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '포켓몬 일본판 확장팩',
                'verbose_name_plural': '포켓몬 일본판 확장팩 목록',
                'db_table': 'japan_expansion',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JapanCardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
                ('source', models.CharField(max_length=100, verbose_name='출처')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricehub.japancard', verbose_name='카드')),
            ],
            options={
                'verbose_name': '포켓몬 일본판 카드 가격',
                'verbose_name_plural': '포켓몬 일본판 카드 가격 목록',
                'db_table': 'japan_card_price',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.AddField(
            model_name='japancard',
            name='expansion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='pricehub.japanexpansion', verbose_name='확장팩'),
        ),
        migrations.CreateModel(
            name='JapanTargetStorePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
                ('store_name', models.CharField(max_length=100, verbose_name='판매처')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcg999_prices', to='pricehub.japancard', verbose_name='카드')),
            ],
            options={
                'verbose_name': '포켓몬 일본판 TCG999 가격',
                'verbose_name_plural': '포켓몬 일본판 TCG999 가격 목록',
                'db_table': 'japan_target_store_price',
                'ordering': ['-collected_at'],
            },
        ),
    ]
