# Generated by Django 5.2.4 on 2026-02-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0010_japancard_japanexpansion_japancardprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='japancard',
            name='mirror_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='미러 타입'),
        ),
        migrations.AlterField(
            model_name='japancard',
            name='rarity',
            field=models.CharField(choices=[('MUR', 'MUR'), ('UR', 'UR'), ('SSR', 'SSR'), ('SAR', 'SAR'), ('SR', 'SR'), ('HR', 'HR'), ('CSR', 'CSR'), ('CHR', 'CHR'), ('AR', 'AR'), ('BWR', 'BWR'), ('마스터볼', '마스터볼'), ('몬스터볼', '몬스터볼'), ('이로치', '이로치'), ('미러', '미러'), ('RRR', 'RRR'), ('RR', 'RR'), ('R', 'R'), ('U', 'U'), ('C', 'C')], max_length=20, verbose_name='레어도'),
        ),
    ]
