# Generated by Django 5.2.4 on 2026-02-09 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0011_japancard_mirror_type_alter_japancard_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='japancardprice',
            name='collected_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='수집일시'),
        ),
    ]
