# Generated by Django 5.2.4 on 2026-04-30 06:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0012_alter_japancardprice_collected_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='japancardprice',
            options={'ordering': ['-collected_at']},
        ),
        migrations.AddField(
            model_name='japancardprice',
            name='condition',
            field=models.CharField(blank=True, default='S', max_length=10),
        ),
        migrations.AddField(
            model_name='japancardprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='japancardprice',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricehub.japancard'),
        ),
        migrations.AlterField(
            model_name='japancardprice',
            name='collected_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='japancardprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='japancardprice',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='japancardprice',
            index=models.Index(fields=['card', 'source', 'condition', '-collected_at'], name='japan_card__card_id_998ff0_idx'),
        ),
    ]
