# Generated by Django 5.2.4 on 2026-05-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0013_alter_japancardprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprice',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
    ]
