# Generated by Django 5.2.4 on 2026-05-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0016_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='selling_price',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(help_text='예: 카드관리프로그램', max_length=100, verbose_name='클라이언트명'),
        ),
    ]
