# Generated by Django 5.2.4 on 2026-05-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0017_remove_card_selling_price_alter_apikey_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='selling_price',
            field=models.PositiveIntegerField(blank=True, help_text='관리자가 설정한 최종 판매가', null=True, verbose_name='판매가'),
        ),
    ]
