# Generated by Django 5.2.4 on 2026-05-27 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0018_card_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onepiecetargetstoreprice',
            name='card',
        ),
        migrations.RemoveField(
            model_name='targetstoreprice',
            name='card',
        ),
        migrations.DeleteModel(
            name='JapanTargetStorePrice',
        ),
        migrations.DeleteModel(
            name='OnePieceTargetStorePrice',
        ),
        migrations.DeleteModel(
            name='TargetStorePrice',
        ),
    ]
