# Generated by Django 5.2.4 on 2026-05-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0019_remove_onepiecetargetstoreprice_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='japancard',
            name='selling_price',
            field=models.PositiveIntegerField(blank=True, help_text='관리자가 설정한 최종 판매가', null=True, verbose_name='판매가'),
        ),
        migrations.AddField(
            model_name='onepiececard',
            name='selling_price',
            field=models.PositiveIntegerField(blank=True, help_text='관리자가 설정한 최종 판매가', null=True, verbose_name='판매가'),
        ),
    ]
