# Generated by Django 5.2.4 on 2026-05-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0020_japancard_selling_price_onepiececard_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='onepiececardprice',
            name='raw_data',
            field=models.JSONField(default=dict, verbose_name='네이버 API 원본 JSON'),
        ),
    ]
