# Generated by Django 5.2.4 on 2026-05-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0021_onepiececardprice_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='selling_price',
            field=models.PositiveIntegerField(default=0, help_text='관리자가 설정한 최종 판매가 (0=미설정)', verbose_name='판매가'),
        ),
        migrations.AlterField(
            model_name='onepiececard',
            name='selling_price',
            field=models.PositiveIntegerField(default=0, help_text='관리자가 설정한 최종 판매가 (0=미설정)', verbose_name='판매가'),
        ),
    ]
