# Generated by Django 5.2.4 on 2026-06-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0025_card_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='modified_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='수정 가격 (일괄 설정 임시값)'),
        ),
        migrations.AlterField(
            model_name='onepiececard',
            name='rarity',
            field=models.CharField(choices=[('SEC', 'SEC'), ('SL', 'SL'), ('SP', 'SP'), ('SR', 'SR'), ('L', 'L'), ('R', 'R'), ('UC', 'UC'), ('C', 'C'), ('P', 'P'), ('MANGA', 'MANGA'), ('P-SEC', 'P-SEC'), ('P-SR', 'P-SR'), ('P-L', 'P-L'), ('P-R', 'P-R'), ('P-UC', 'P-UC'), ('P-C', 'P-C')], max_length=20, verbose_name='레어도'),
        ),
    ]
