# Generated by Django 5.2.4 on 2026-06-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0026_card_modified_price_alter_onepiececard_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='onepiececard',
            name='modified_price',
            field=models.PositiveIntegerField(default=0, help_text='일괄 설정 실행 시 임시 저장. 하락 시 작업자 확인 후 반영.', verbose_name='수정 가격 (일괄 설정 임시값)'),
        ),
    ]
