# Generated by Django 5.2.4 on 2026-06-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0027_onepiececard_modified_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='latest_raw_data',
            field=models.JSONField(blank=True, help_text='가격 수집 시 자동 업데이트. bulk_price 조회에 사용.', null=True, verbose_name='최신 수집 raw_data 캐시'),
        ),
        migrations.AddField(
            model_name='onepiececard',
            name='latest_raw_data',
            field=models.JSONField(blank=True, help_text='가격 수집 시 자동 업데이트. bulk_price 조회에 사용.', null=True, verbose_name='최신 수집 raw_data 캐시'),
        ),
    ]
