# Generated by Django 5.2.4 on 2026-06-30 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0028_card_latest_raw_data_onepiececard_latest_raw_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigimonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_product_code', models.CharField(max_length=50, unique=True, verbose_name='상품코드')),
                ('card_number', models.CharField(max_length=20, verbose_name='카드번호')),
                ('name', models.CharField(max_length=100, verbose_name='카드명')),
                ('rarity', models.CharField(choices=[('SEC', 'SEC'), ('SR', 'SR'), ('R', 'R'), ('U', 'U'), ('C', 'C'), ('P', 'P'), ('PR', 'PR'), ('L', 'L'), ('DR', 'DR'), ('AC', 'AC')], max_length=20, verbose_name='레어도')),
                ('card_type', models.CharField(blank=True, max_length=20, verbose_name='카드타입')),
                ('card_level', models.CharField(blank=True, max_length=10, verbose_name='카드레벨')),
                ('is_parallel', models.BooleanField(default=False, verbose_name='패러렐')),
                ('is_scarce', models.BooleanField(default=False, verbose_name='희소')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='이미지 URL')),
                ('is_favorite', models.BooleanField(db_index=True, default=False, verbose_name='즐겨찾기')),
                ('selling_price', models.PositiveIntegerField(default=0, help_text='관리자가 설정한 최종 판매가 (0=미설정)', verbose_name='판매가')),
                ('modified_price', models.PositiveIntegerField(default=0, help_text='일괄 설정 실행 시 임시 저장. 하락 시 작업자 확인 후 반영.', verbose_name='수정 가격 (일괄 설정 임시값)')),
                ('latest_raw_data', models.JSONField(blank=True, help_text='가격 수집 시 자동 업데이트. bulk_price 조회에 사용.', null=True, verbose_name='최신 수집 raw_data 캐시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '디지몬 한글판 카드',
                'verbose_name_plural': '디지몬 한글판 카드 목록',
                'db_table': 'digimon_card',
                'ordering': ['expansion', 'card_number'],
            },
        ),
        migrations.CreateModel(
            name='DigimonExpansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='확장팩 코드')),
                ('name', models.CharField(max_length=100, verbose_name='확장팩명')),
                ('category_id', models.IntegerField(help_text='digimoncard.co.kr 카테고리 ID', unique=True, verbose_name='카테고리 ID')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='출시일')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '디지몬 한글판 확장팩',
                'verbose_name_plural': '디지몬 한글판 확장팩 목록',
                'db_table': 'digimon_expansion',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['expansion', 'card_number'], 'verbose_name': '포켓몬 한글판 카드', 'verbose_name_plural': '포켓몬 한글판 카드 목록'},
        ),
        migrations.AlterModelOptions(
            name='cardprice',
            options={'ordering': ['-collected_at'], 'verbose_name': '포켓몬 한글판 가격', 'verbose_name_plural': '포켓몬 한글판 가격 목록'},
        ),
        migrations.AlterModelOptions(
            name='expansion',
            options={'ordering': ['-release_date', '-created_at'], 'verbose_name': '포켓몬 한글판 확장팩', 'verbose_name_plural': '포켓몬 한글판 확장팩 목록'},
        ),
        migrations.AlterModelOptions(
            name='japancardprice',
            options={'ordering': ['-collected_at'], 'verbose_name': '포켓몬 일본판 가격', 'verbose_name_plural': '포켓몬 일본판 가격 목록'},
        ),
        migrations.AlterModelOptions(
            name='onepiececard',
            options={'ordering': ['expansion', 'card_number'], 'verbose_name': '원피스 한글판 카드', 'verbose_name_plural': '원피스 한글판 카드 목록'},
        ),
        migrations.AlterModelOptions(
            name='onepiececardprice',
            options={'ordering': ['-collected_at'], 'verbose_name': '원피스 한글판 가격', 'verbose_name_plural': '원피스 한글판 가격 목록'},
        ),
        migrations.AlterModelOptions(
            name='onepieceexpansion',
            options={'ordering': ['-release_date', '-created_at'], 'verbose_name': '원피스 한글판 확장팩', 'verbose_name_plural': '원피스 한글판 확장팩 목록'},
        ),
        migrations.CreateModel(
            name='DigimonCardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
                ('source', models.CharField(max_length=100, verbose_name='판매처')),
                ('raw_data', models.JSONField(default=dict, verbose_name='네이버 API 원본 JSON')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricehub.digimoncard', verbose_name='카드')),
            ],
            options={
                'verbose_name': '디지몬 한글판 가격',
                'verbose_name_plural': '디지몬 한글판 가격 목록',
                'db_table': 'digimon_card_price',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='expansion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='pricehub.digimonexpansion', verbose_name='확장팩'),
        ),
    ]
