# Generated by Django 5.2.4 on 2026-07-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0030_digimoncard_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_teukil',
            field=models.BooleanField(db_index=True, default=False, verbose_name='특일'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('UR', 'UR'), ('SSR', 'SSR'), ('SR', 'SR'), ('RR', 'RR'), ('RRR', 'RRR'), ('CHR', 'CHR'), ('CSR', 'CSR'), ('BWR', 'BWR'), ('AR', 'AR'), ('SAR', 'SAR'), ('HR', 'HR'), ('MUR', 'MUR'), ('MA', 'MA'), ('K', 'K'), ('R', 'R'), ('U', 'U'), ('C', 'C'), ('몬스터볼', '몬스터볼'), ('마스터볼', '마스터볼'), ('볼 미러', '볼 미러'), ('타입 미러', '타입 미러'), ('로켓단 미러', '로켓단 미러'), ('이로치', '이로치'), ('미러', '미러')], max_length=20, verbose_name='레어도'),
        ),
    ]
