# Generated by Django 5.2.4 on 2026-07-02 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pricehub', '0031_card_is_teukil_alter_card_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 2026년 7월 매입', max_length=200, verbose_name='매입리스트명')),
                ('game_type', models.CharField(choices=[('pokemon_kr', '포켓몬 한글판'), ('pokemon_jp', '포켓몬 일본판'), ('onepiece_kr', '원피스 한글판'), ('digimon_kr', '디지몬 한글판')], db_index=True, max_length=20, verbose_name='게임 구분')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('default_purchase_ratio', models.DecimalField(decimal_places=2, default=50, help_text='카드를 추가할 때 추천 매입가를 계산하는 기본 비율. 보통 판매가의 50%.', max_digits=5, verbose_name='기본 매입가 비율(%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '매입리스트',
                'verbose_name_plural': '매입리스트 목록',
                'db_table': 'purchase_list',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='카드 ID')),
                ('selling_price_snapshot', models.PositiveIntegerField(default=0, verbose_name='추가 시점 판매가')),
                ('purchase_ratio', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='적용 매입가 비율(%)')),
                ('recommended_purchase_price', models.PositiveIntegerField(default=0, help_text='판매가 × 매입가 비율로 자동 계산됨', verbose_name='추천 매입가')),
                ('purchase_price', models.PositiveIntegerField(blank=True, help_text='가격 관리자가 최종 결정한 매입가. 비어있으면 미확정(추천가만 있는 상태).', null=True, verbose_name='확정 매입가')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='추가일시')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='매입가 확정일시')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='카드 종류')),
                ('purchase_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricehub.purchaselist', verbose_name='매입리스트')),
            ],
            options={
                'verbose_name': '매입리스트 항목',
                'verbose_name_plural': '매입리스트 항목 목록',
                'db_table': 'purchase_list_item',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='purchase_li_content_a8e6d2_idx')],
                'unique_together': {('purchase_list', 'content_type', 'object_id')},
            },
        ),
    ]
