# Generated by Django 5.2.4 on 2026-07-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0033_hash_existing_api_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(max_length=64, unique=True, verbose_name='API Key 해시 (SHA-256)'),
        ),
    ]
