# Generated by Django 5.2.4 on 2026-07-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0034_alter_apikey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='latest_market_price',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='가격 수집 시 자동 업데이트(경쟁사 최저가, 자기 매장 제외). 카드마다 가격 히스토리를 서브쿼리로 뒤지지 않도록 하는 캐시 컬럼 — 목록 정렬·저가 경고 판정에 사용.', null=True, verbose_name='최신 시장 최저가 캐시'),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='latest_market_price',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='가격 수집 시 자동 업데이트(경쟁사 최저가, 자기 매장 제외). 카드마다 가격 히스토리를 서브쿼리로 뒤지지 않도록 하는 캐시 컬럼 — 목록 정렬·저가 경고 판정에 사용.', null=True, verbose_name='최신 시장 최저가 캐시'),
        ),
        migrations.AddField(
            model_name='onepiececard',
            name='latest_market_price',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='가격 수집 시 자동 업데이트(경쟁사 최저가, 자기 매장 제외). 카드마다 가격 히스토리를 서브쿼리로 뒤지지 않도록 하는 캐시 컬럼 — 목록 정렬·저가 경고 판정에 사용.', null=True, verbose_name='최신 시장 최저가 캐시'),
        ),
    ]
