# Generated by Django 5.2.4 on 2026-07-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0036_backfill_latest_market_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RarityPurchasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('pokemon_kr', '포켓몬 한글판'), ('pokemon_jp', '포켓몬 일본판'), ('onepiece_kr', '원피스 한글판'), ('digimon_kr', '디지몬 한글판')], db_index=True, max_length=20, verbose_name='게임 구분')),
                ('rarity', models.CharField(max_length=50, verbose_name='레어도')),
                ('price', models.PositiveIntegerField(default=0, help_text='이 레어도의 카드를 개별 등록 없이 매입할 때 적용할 고정 금액(원)', verbose_name='매입 고정가')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '레어도별 매입 고정가',
                'verbose_name_plural': '레어도별 매입 고정가 목록',
                'db_table': 'rarity_purchase_price',
                'ordering': ['game_type', 'rarity'],
                'unique_together': {('game_type', 'rarity')},
            },
        ),
    ]
