# Generated by Django 5.2.4 on 2026-07-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0036_backfill_latest_market_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RarityPurchaseRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('pokemon_kr', '포켓몬 한글판'), ('pokemon_jp', '포켓몬 일본판'), ('onepiece_kr', '원피스 한글판'), ('digimon_kr', '디지몬 한글판')], db_index=True, max_length=20, verbose_name='게임 구분')),
                ('rarity', models.CharField(max_length=50, verbose_name='레어도')),
                ('ratio', models.DecimalField(decimal_places=2, default=30, help_text='시장 최저가 대비 매입가 비율', max_digits=5, verbose_name='매입가 비율(%)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '레어도별 매입가 비율',
                'verbose_name_plural': '레어도별 매입가 비율 목록',
                'db_table': 'rarity_purchase_ratio',
                'ordering': ['game_type', 'rarity'],
                'unique_together': {('game_type', 'rarity')},
            },
        ),
    ]
