# Generated by Django 5.2.4 on 2026-07-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0038_alter_onepiececard_rarity'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='digimoncardprice',
            index=models.Index(fields=['card', '-collected_at'], name='digimon_car_card_id_8f36ea_idx'),
        ),
        migrations.AddIndex(
            model_name='digimoncardprice',
            index=models.Index(fields=['collected_at'], name='digimon_car_collect_cfd5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='onepiececardprice',
            index=models.Index(fields=['card', '-collected_at'], name='onepiece_ca_card_id_476c80_idx'),
        ),
        migrations.AddIndex(
            model_name='onepiececardprice',
            index=models.Index(fields=['collected_at'], name='onepiece_ca_collect_c084ce_idx'),
        ),
    ]
