# Generated by Django 5.2.4 on 2026-07-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0039_digimoncardprice_digimon_car_card_id_8f36ea_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='reviewed_market_price',
            field=models.PositiveIntegerField(blank=True, help_text='이 값이 latest_market_price와 같으면 저가 경고 목록에서 제외됨 — 작업자가 이미 그 시장가를 보고 판매가를 결정했다는 뜻. 다음 수집에서 시장가가 달라지면(필터링으로 못 거르는 오매칭이 해소/변경되면) 다시 노출됨.', null=True, verbose_name='저가 경고 확인 완료 시점의 시장 최저가'),
        ),
        migrations.AddField(
            model_name='digimoncard',
            name='reviewed_market_price',
            field=models.PositiveIntegerField(blank=True, help_text='이 값이 latest_market_price와 같으면 저가 경고 목록에서 제외됨 — 작업자가 이미 그 시장가를 보고 판매가를 결정했다는 뜻. 다음 수집에서 시장가가 달라지면(필터링으로 못 거르는 오매칭이 해소/변경되면) 다시 노출됨.', null=True, verbose_name='저가 경고 확인 완료 시점의 시장 최저가'),
        ),
        migrations.AddField(
            model_name='onepiececard',
            name='reviewed_market_price',
            field=models.PositiveIntegerField(blank=True, help_text='이 값이 latest_market_price와 같으면 저가 경고 목록에서 제외됨 — 작업자가 이미 그 시장가를 보고 판매가를 결정했다는 뜻. 다음 수집에서 시장가가 달라지면(필터링으로 못 거르는 오매칭이 해소/변경되면) 다시 노출됨.', null=True, verbose_name='저가 경고 확인 완료 시점의 시장 최저가'),
        ),
    ]
