# Generated by Django 5.2.4 on 2026-07-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0040_card_reviewed_market_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onepiececard',
            name='rarity',
            field=models.CharField(choices=[('SEC', 'SEC'), ('SL', 'SL'), ('SP', 'SP'), ('SR', 'SR'), ('L', 'L'), ('R', 'R'), ('UC', 'UC'), ('C', 'C'), ('P', 'P'), ('MANGA', 'MANGA'), ('REDMANGA', 'REDMANGA'), ('P-SEC', 'P-SEC'), ('P-SR', 'P-SR'), ('P-L', 'P-L'), ('P-R', 'P-R'), ('P-UC', 'P-UC'), ('P-C', 'P-C'), ('D', 'D'), ('P-D', 'P-D')], max_length=20, verbose_name='레어도'),
        ),
    ]
