# Generated by Django 5.2.4 on 2026-07-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricehub', '0041_alter_onepiececard_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='digimoncard',
            name='needs_rarity_check',
            field=models.BooleanField(db_index=True, default=False, help_text='신규 카드번호가 같은 확장팩 안에서 3번째 인쇄(V2)까지 나온 경우 — 희소/스페셜 중 어느 쪽인지 크롤링만으론 알 수 없어 이미지 확인 필요.', verbose_name='레어도 확인 필요'),
        ),
    ]
